# yaml-language-server: $schema=https://ghalactic.github.io/provision-github-tokens/schema/requester.v1.schema.json

tokens:
  readMetadata:
    repos:
      - provision-github-tokens-ci-consumer
    permissions:
      metadata: read
  readActions:
    repos:
      - provision-github-tokens-ci-consumer
    permissions:
      secrets: read
  unauthorizedToken:
    repos:
      - provision-github-tokens-ci-consumer
    permissions:
      contents: write

provision:
  secrets:
    READ_METADATA_TOKEN:
      token: readMetadata
      github:
        repo:
          actions: true
          environments: ["*"]
    READ_SECRETS_TOKEN:
      token: readActions
      github:
        repo:
          actions: true
    UNAUTHORIZED_PROVISION:
      token: readMetadata
      github:
        repos:
          ghalactic/provision-github-tokens:
            actions: true
    PARTIALLY_AUTHORIZED_PROVISION:
      token: readMetadata
      github:
        repo:
          actions: true
        repos:
          ghalactic/provision-github-tokens:
            actions: true
